#! /bin/bash
touch Dockerfile
echo "FROM ubuntu" >> Dockerfile
docker build -t envariable .
docker images
docker login --username $username --password $password
docker tag envariable:latest pranjali58/nautjos:envar
docker push pranjali58/nautjos:envar

